#!/bin/bash 

HOME=/home/speed/coutinho/

# program directory(absolute path)
DIR_PROG=${HOME}/datacutter/void_3.1/samples/termination_test

# Void directory
DIR_DS=${HOME}/void_3.1
# Filters directory
DIR_FILTERS=${DIR_PROG}

# the machine where manager is
DISPLAY=asteria:0.0

#uncomment to debug
#if [ `hostname` = "urano" ] 
#then
	DEBUG=0
#fi

# manger binary
BIN="main"
# debugger command line
DEBUGGER="ddd"

#End of header
#modify below this only if you know what youre doing
##################################################################################
cd ${DIR_PROG}
export LD_LIBRARY_PATH=${DIR_DS}:${DIR_FILTERS}:${LD_LIBRARY_PATH}

# calls application
# format: ./<manager binary>  <this file name, initScript>
if [ "$DEBUG" = 1 ]; then

#	echo -e "break main\n run $*\n break initGlobalTermination\n break verifyGlobalTermination\n 
#	break initTerminationDetection\n break beginTerminationDetection\n 
#	break terminationDetectionRound\n" > start.gdb 
	#break 	updateTermStreamToEmpty\n" > start.gdb
	echo -e "break main\n run $*\n" > start.gdb

	export DISPLAY=$DISPLAY
	${DEBUGGER} ${BIN} -x start.gdb 
#-x start.gdb
else
	./${BIN} $@
fi
