#!/bin/bash 

# program directory(absolute path)
DIR_PROG=${HOME}/void/void_3.1/FilterMaker/samples/sample_matlab_hellow_word/

# Void directory
DIR_DS=${HOME}/void/void_3.1/
# Filters directory
DIR_FILTERS=${DIR_PROG}

# the machine where manager is
DISPLAY=clyde:0.0

#uncomment to debug
#if [ `hostname` = "dc06.bmi.ohio-state.edu" ] 
#then
	DEBUG=1
#fi

# manger binary
BIN="main"
# debugger command line
DEBUGGER="ddd"

#End of header
#modify below this only if you know what youre doing
##################################################################################
cd ${DIR_PROG}
MATLAB_LIBRARY="${HOME}/MCR/v72/runtime/glnx86/:${HOME}/MCR/v72/sys/os/glnx86/:${HOME}/MCR/v72/sys/java/jre/glnx86/jre1.5.0/lib/i386/native_threads/:${HOME}/MCR/v72/sys/java/jre/glnx86/jre1.5.0/lib/i386/client/:${HOME}/MCR/v72/sys/java/jre/glnx86/jre1.5.0/lib/i386/:${HOME}/MCR/v72/bin/glnx86/"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DIR_DS}:${DIR_FILTERS}:${MATLAB_LIBRARY}"


# calls application
# format: ./<manager binary>  <this file name, initScript>
if [ "$DEBUG" = 1 ]; then

	echo -e "break main\n run $*\n break FilterData.c:40\n" > start.gdb

	export DISPLAY=$DISPLAY
	${DEBUGGER} ${BIN} -x start.gdb 
#-x start.gdb
else
	./${BIN} $@ &> log/errorFilter$$.txt
fi
