#!/bin/bash 

# program directory(absolute path)
DIR_PROG=${HOME}/sci_workflow/trunk/void_3.1/samples/labeled_stream_return_label

# Void directory
DIR_DS=${HOME}/sci_workflow/trunk/void_3.1
# Filters directory
DIR_FILTERS=${DIR_PROG}

# the machine where manager is
DISPLAY=:0.0

#uncomment to debug
#DEBUG=1

# manger binary
BIN="main"
# debugger command line
DEBUGGER="ddd"
# the source file that contains the call to initDs() (to generate gdb startup file)
MAIN_SOURCE_FILE="main.c"

#End of header
#modify below this only if you know what youre doing
##################################################################################
cd ${DIR_PROG}
export LD_LIBRARY_PATH=${DIR_DS}:${DIR_FILTERS}:${LD_LIBRARY_PATH}

# calls application
# format: ./<manager binary>  <this file name, initScript>
if [ "$DEBUG" = 1 ]; then

	echo -e "break main\n run $*\n break FilterData.c:69" > start.gdb
#	${DIR_DS}/generateGdbStartup.sh ${MAIN_SOURCE_FILE} "$*" > start.gdb

	export DISPLAY=$DISPLAY
	${DEBUGGER} ${BIN} -x start.gdb 
else
	./${BIN} $@ > ./log/$$.txt
fi

