#!/bin/bash 

# program directory(absolute path)
DIR_PROG=${HOME}/void/void_3.1/samples/sample_print

# Void directory
DIR_DS=${HOME}/void/void_3.1
#DIR_DS=./
#Filters directory
DIR_FILTERS=${DIR_PROG}
#DIR_FILTERS=./

# the machine where manager is
DISPLAY=clyde:0

#uncomment to debug
#DEBUG=1

# manger binary
BIN="main"
# debugger command line
DEBUGGER="ddd"
#DEBUGGER="xterm -e gdb"

#End of header
#modify below this only if you know what youre doing
##################################################################################
cd ${DIR_PROG}
export LD_LIBRARY_PATH=${DIR_DS}:${DIR_FILTERS}:${LD_LIBRARY_PATH}
# calls application
# format: ./<manager binary>  <this file name, initScript>
if [ "$DEBUG" = 1 ]; then

	echo -e "break main\n run $*\n break FilterData.c:34\n" > start.gdb

	export DISPLAY=$DISPLAY
	${DEBUGGER} ${BIN} -x start.gdb 
else
	./${BIN} $@ > log/$$.bla
fi
